name: build and deploy studentfe

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          dir: student-fe
          cmd: install

      - name: Build the application
        uses: borales/actions-yarn@v4
        with:
          dir: student-fe
          cmd: build

      - name: Configure s3cmd
        run: |
          echo ${{ secrets.S3CMD_CONFIG }} | base64 -d > ~/.s3cfg
      - name: Install s3cmd
        run: sudo apt-get install -y s3cmd
      - name: Upload to S3
        run: |
          s3cmd sync --recursive --acl-public --no-mime-magic --guess-mime-type --delete-removed student-fe/out/ s3://student-fe
